# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Email_pages.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QApplication, QWidget, QDialog, QLabel, QLineEdit, QPushButton, \
    QGridLayout, QVBoxLayout, QHBoxLayout, QMessageBox,QMainWindow
from PyQt5.QtCore import QCoreApplication
import sys
from PyQt5.QtCore import Qt
import qtawesome
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets


class Email_page():
    def __init__(self):
        super(Email_page,self).__init__()
        self.sender_label = QLabel('发件人:', self)
        self.address_label = QLabel('收件人:', self)
        self.theme_label = QLabel('主题:', self)
        self.body_label = QLabel('正文:', self)
        self.accessory_label = QLabel('附件:', self)
        self.sender_label_line = QLineEdit(self)
        self.address_line = QLineEdit(self)
        self.theme_line = QLineEdit(self)
        self.body_line = QLineEdit(self)
        self.accessory_line = QLineEdit(self)
        self.send_button = QPushButton('Send', self)
        self.cancel_button = QPushButton('Cancel', self)

        self.sender_layout = QHBoxLayout()
        self.address_layout = QHBoxLayout()
        self.theme_layout = QHBoxLayout()
        self.accessory_layout = QVBoxLayout()



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "发件人"))
        self.label_2.setText(_translate("Dialog", "主题"))
        self.label_3.setText(_translate("Dialog", "收件人"))
        self.label_4.setText(_translate("Dialog", "正文"))
        self.label_5.setText(_translate("Dialog", "附件"))

